# 20200805 今日份的 debug

## 第一次跟踪

昨天的方案没有作用，我又继续单步跟踪，跟踪到了 `kernel-hal-unix/src/lib.rs:46`，出问题的代码为：

```rust
impl Thread {
    #[export_name = "hal_thread_spawn"]
    pub fn spawn(
        future: Pin<Box<dyn Future<Output = ()> + Send + 'static>>,
        _vmtoken: usize,
    ) -> Self {
        async_std::task::spawn(future);   // error occurs here
        Thread { thread: 0 }
    }
}
```

进一步跟踪，到了 `async-std` 这个库的 `src/task/builder.rs:64` 位置：

```rust
impl Builder {
    /// Spawns a task with the configured settings.
    #[cfg(not(target_os = "unknown"))]
    pub fn spawn<F, T>(self, future: F) -> io::Result<JoinHandle<T>>
    where
        F: Future<Output = T> + Send + 'static,
        T: Send + 'static,
    {
        let wrapped = self.build(future);

        kv_log_macro::trace!("spawn", {
            task_id: wrapped.tag.id().0,
            parent_task_id: TaskLocalsWrapper::get_current(|t| t.id().0).unwrap_or(0),
        });

        let task = wrapped.tag.task().clone();
        let smol_task = smol::Task::spawn(wrapped).into();  // error occurs here

        Ok(JoinHandle::new(smol_task, task))
    }
}
```

再进一步跟踪，到了 `smol`(0.1.18) 库的 `src/multitask.rs:156` 位置：

```rust
impl Queue {
    /// Spawns a future onto this queue.
    ///
    /// Returns a [`Task`] handle for the spawned task.
    pub fn spawn<T: Send + 'static>(
        &self,
        future: impl Future<Output = T> + Send + 'static,
    ) -> Task<T> {
        let global = self.global.clone();

        // The function that schedules a runnable task when it gets woken up.
        let schedule = move |runnable| {
            if WORKER.is_set() {
                WORKER.with(|w| {
                    if Arc::ptr_eq(&global, &w.global) {
                        if let Err(err) = w.shard.push(runnable) {
                            global.queue.push(err.into_inner()).unwrap();
                        }
                    } else {
                        global.queue.push(runnable).unwrap();
                    }
                });
            } else {
                global.queue.push(runnable).unwrap();
            }

            global.notify();
        };

        // Create a task, push it into the queue by scheduling it, and return its `Task` handle.
        let (runnable, handle) = async_task::spawn(future, schedule, ());
        runnable.schedule();  // error occurs here
        Task(Some(handle))
    }
}
```

再再进一步跟踪，到了 `async-task` 库的 `src/raw.rs:408` 位置：

```rust
impl<F, R, S, T> RawTask<F, R, S, T>
where
    F: Future<Output = R> + 'static,
    S: Fn(Task<T>) + Send + Sync + 'static,
{
    /// Schedules a task for running.
    ///
    /// This function doesn't modify the state of the task. It only passes the task reference to
    /// its schedule function.
    unsafe fn schedule(ptr: *const ()) {
        let raw = Self::from_ptr(ptr);

        // If the schedule function has captured variables, create a temporary waker that prevents
        // the task from getting deallocated while the function is being invoked.
        let _waker;
        if mem::size_of::<S>() > 0 {
            _waker = Waker::from_raw(Self::clone_waker(ptr));
        }

        let task = Task {
            raw_task: NonNull::new_unchecked(ptr as *mut ()),
            _marker: PhantomData,
        };
        (*raw.schedule)(task);    // error occurs here
    }
}
```

再再再进一步跟踪，又回到了 `smol` 库的 `src/multitask.rs:151` 位置：

```rust
        let schedule = move |runnable| {
            if WORKER.is_set() {
                WORKER.with(|w| {
                    if Arc::ptr_eq(&global, &w.global) {
                        if let Err(err) = w.shard.push(runnable) {
                            global.queue.push(err.into_inner()).unwrap();
                        }
                    } else {
                        global.queue.push(runnable).unwrap();
                    }
                });
            } else {
                global.queue.push(runnable).unwrap();
            }

            global.notify();    // error occurs here
        };
```

再再再再进一步跟踪，到了 `smol` 的 `src/multitask.rs:41` 位置：

```rust
impl Global {
    /// Notifies a sleeping worker.
    fn notify(&self) {
        if !self
            .notified
            .compare_and_swap(false, true, Ordering::SeqCst)
        {
            let callback = self.sleepers.lock().unwrap().notify();
            if let Some(cb) = callback {
                cb.call();      // error occurs here
            }
        }
    }
}
```

再再再再再进一步跟踪，到了 `smol` 的 `src/run.rs:106` 位置：

```rust
pub fn run<T>(future: impl Future<Output = T>) -> T {
    let parker = Parker::new();

    let unparker = parker.unparker();
    let worker = QUEUE.worker(move || unparker.unpark());   // error occurs here

    // ...
}
```

再再再再再再进一步跟踪，到了 `smol` 的 `src/parking.rs:268` 位置：

```rust
impl Inner {
    pub fn unpark(&self) {
        // To ensure the unparked thread will observe any writes we made before this call, we must
        // perform a release operation that `park` can synchronize with. To do that we must write
        // `NOTIFIED` even if `state` is already `NOTIFIED`. That is why this must be a swap rather
        // than a compare-and-swap that returns if it reads `NOTIFIED` on failure.
        let state = match self.state.swap(NOTIFIED, SeqCst) {
            EMPTY => return,    // no one was waiting
            NOTIFIED => return, // already unparked
            state => state,     // gotta go wake someone up
        };

        // There is a period between when the parked thread sets `state` to `PARKED` (or last
        // checked `state` in the case of a spurious wakeup) and when it actually waits on `cvar`.
        // If we were to notify during this period it would be ignored and then when the parked
        // thread went to sleep it would never wake up. Fortunately, it has `lock` locked at this
        // stage so we can acquire `lock` to wait until it is ready to receive the notification.
        //
        // Releasing `lock` before the call to `notify_one` means that when the parked thread wakes
        // it doesn't get woken only to have to wait for us to release `lock`.
        drop(self.lock.lock().unwrap());

        if state == PARKED {
            self.cvar.notify_one();     // error occurs here
        } else {
            Reactor::get().notify();
        }
    }
}
```

而 `Inner` 的定义为：

```rust
struct Inner {
    state: AtomicUsize,
    lock: Mutex<()>,
    cvar: Condvar,
}
```

其中，`Condvar` 是系统库 `std::sync::Condvar` 的内容

最终就跟踪到这里了，再进一步跟踪就是 GLIBC 了

场面一度陷入僵局，我决定重新跟踪一下，这次是从代码下手，而不是用 GDB

## 第二次跟踪

昨天的代码问题出在 `linux-loader/src/lib.rs` 的 `run` 函数：

```rust
pub fn run(args: Vec<String>, envs: Vec<String>, rootfs: Arc<dyn FileSystem>) -> Arc<Process> {
    let job = Job::root();
    let proc = Process::create_linux(&job, rootfs.clone()).unwrap();
    let thread = Thread::create_linux(&proc).unwrap();
    let loader = LinuxElfLoader {
        #[cfg(feature = "std")]
        syscall_entry: kernel_hal_unix::syscall_entry as usize,
        #[cfg(not(feature = "std"))]
        syscall_entry: 0,
        stack_pages: 8,
        root_inode: rootfs.root_inode(),
    };
    let inode = rootfs.root_inode().lookup(&args[0]).unwrap();
    let data = inode.read_as_vec().unwrap();
    let (entry, sp) = loader.load(&proc.vmar(), &data, args, envs).unwrap();

    thread
        .start(entry, sp, 0, 0, spawn)  // error occurs here
        .expect("failed to start main thread");
    proc
}
```

`start` 应该没问题，问题处在 `spawn` 上，而 `spawn` 是在该文件内定义的一个函数：

```rust
fn spawn(thread: Arc<Thread>) {
    let vmtoken = thread.proc().vmar().table_phys();
    let future = async move {
        loop {
            let mut cx = thread.wait_for_run().await;
            trace!("go to user: {:#x?}", cx);
            kernel_hal::context_run(&mut cx);
            trace!("back from user: {:#x?}", cx);
            let mut exit = false;
            match cx.trap_num {
                0x100 => exit = handle_syscall(&thread, &mut cx.general).await,
                0x20..=0x3f => {
                    kernel_hal::InterruptManager::handle(cx.trap_num as u8);
                    if cx.trap_num == 0x20 {
                        kernel_hal::yield_now().await;
                    }
                }
                0xe => {
                    let vaddr = kernel_hal::fetch_fault_vaddr();
                    let flags = if cx.error_code & 0x2 == 0 {
                        MMUFlags::READ
                    } else {
                        MMUFlags::WRITE
                    };
                    error!("page fualt from user mode {:#x} {:#x?}", vaddr, flags);
                    let vmar = thread.proc().vmar();
                    match vmar.handle_page_fault(vaddr, flags) {
                        Ok(()) => {}
                        Err(_) => {
                            panic!("Page Fault from user mode {:#x?}", cx);
                        }
                    }
                }
                _ => panic!("not supported interrupt from user mode. {:#x?}", cx),
            }
            thread.end_running(cx);
            if exit {
                break;
            }
        }
    };
    kernel_hal::Thread::spawn(Box::pin(future), vmtoken);   // error occurs here
}
```

该函数最终执行了 `kernel_hal::Thread::spawn`，与之前用 GDB 跟踪到的结果一致

我觉得第三方库、系统库、GLIBC 出问题的几率不大，因此所以我想先从这里下手

我怀疑传入的参数 `future` 有问题，断点打到 `future` 这个闭包里面，继续跟踪

跟踪了一下，函数好像运行不到这里，为什么？？？

在 `spawn` 里打断点后，`kernel_hal::Thread::spawn` 就能正常运行了，为什么？？？

最后问题又回到 `smol` 库里面了：

```rust
pub fn run<T>(future: impl Future<Output = T>) -> T {
    let parker = Parker::new();

    let unparker = parker.unparker();
    let worker = QUEUE.worker(move || unparker.unpark());

    // Create a waker that triggers an I/O event in the thread-local scheduler.
    let unparker = parker.unparker();
    let waker = async_task::waker_fn(move || unparker.unpark());
    let cx = &mut Context::from_waker(&waker);
    futures_util::pin_mut!(future);

    // Set up tokio if enabled.
    context::enter(|| {
        WORKER.set(&worker, || {
            'start: loop {
                // Poll the main future.
                if let Poll::Ready(val) = future.as_mut().poll(cx) {
                    return val;
                }

                for _ in 0..200 {
                    if !worker.tick() {
                        parker.park();      // error occurs here
                        continue 'start;
                    }
                }

                // Process ready I/O events without blocking.
                parker.park_timeout(Duration::from_secs(0));
            }
        })
    })
}
```

我大概知道问题所在了，在 `linux-loader/src/main.rs` 中需要等待进程结束的 SIGNAL，但是一直等不到，然后就...段错误...？

好像的确是这样子的，执行 `/bin/busybox ls` 的话结果会秒出，而执行 `/bin/gcc` 时会等待一会，然后才报段错误，所以我认为是 GCC 启动卡住了，导致 `smol` 一直在等待

那么下一步就是查进程是从哪启动的了吧，这里可能需要参考 rCore 了

补充：我写了一个 Hello World，静态链接编译之后放到 rootfs 里面，结果也无法运行，报段错误，真的需要查一下了

问题又转化回：无法运行静态链接的程序 了

刚才开会，经过王润基学长提醒，在 LibOS 下只能运行动态链接到 `libc-libos.so` 的程序，所以理论上是无法运行静态链接的程序的，除非跑在裸机下

该问的还是要问呀，没有及时问学长导致我浪费了昨天一晚上和今天一上午时间

一个小问题解决了，运行自己写的程序的方法，如编译 `tmp.c` 时，使用如下命令：

```bash
gcc tmp.c -Wl,--dynamic-linker=/lib/ld-musl-x86_64.so.1
```

然后把编译得到的 `a.out` 复制到 `rootfs/bin/` 即可正常运行

记录一下得到的结果

> zCore git:master ❯ cargo run -p linux-loader /bin/hello
>
> Finished dev [unoptimized + debuginfo] target(s) in 0.06s
>
> Running \`target/debug/linux-loader /bin/hello\`
>
> Hello, World
